### ISSUE TITLE
Inspector-puppeteer is not killing chrome processes

### ISSUE THREAD

**Issue by FeliceGeracitano** [saksdirect/webperf-dashboard#72]
Inspector-puppeteer pod log:
<img width="607" alt="Screenshot 2019-03-22 at 10 26 03" src="https://user-images.githubusercontent.com/6695231/54813539-0edde180-4c8e-11e9-88bb-81dc797bfb87.png">

Inspector-puppeteer should take care of killing chrome instances, let's try with:
```js
await browser.close();
```
source: https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-class-browser

**Comment by rbelling** [comment]
will try it out, thanks!
